"use client";

import { Download, FileText, Printer } from "lucide-react";

interface DownloadReceiptProps {
  trackId: string;
  facultyName: string;
  senderName: string;
  senderEmail: string;
  subject: string;
  message: string;
  date?: string;
}

export default function DownloadReceipt({
  trackId,
  facultyName,
  senderName,
  senderEmail,
  subject,
  message,
  date = new Date().toLocaleString(),
}: DownloadReceiptProps) {
  const downloadAsWord = () => {
    const html = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>Inquiry Receipt</title></head>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #eee; padding: 40px; border-radius: 10px;">
          <h1 style="color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 10px;">Official Inquiry Receipt</h1>
          <p><strong>Tracking ID:</strong> <span style="font-family: monospace; background: #f4f4f4; padding: 2px 5px; font-weight: bold;">${trackId}</span></p>
          <p><strong>Date Submitted:</strong> ${date}</p>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;"/>
          <p><strong>To Faculty:</strong> ${facultyName}</p>
          <p><strong>From:</strong> ${senderName} (${senderEmail})</p>
          <p><strong>Subject:</strong> ${subject}</p>
          <div style="margin-top: 20px; padding: 20px; background: #f9f9f9; border-left: 4px solid #1a73e8;">
            <p><strong>Message Content:</strong></p>
            <p style="white-space: pre-wrap;">${message}</p>
          </div>
          <p style="margin-top: 40px; font-size: 11px; color: #888; text-align: center; border-top: 1px solid #eee; pt: 10px;">
            This is an official record generated by the Faculty & Staff Information Portal.
            <br/>
            Track status at: ${typeof window !== 'undefined' ? window.location.origin : ''}/inquiry/${trackId}
          </p>
        </div>
      </body>
      </html>
    `;
    const blob = new Blob(['\ufeff', html], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Inquiry_Receipt_${trackId.substring(0, 8)}.doc`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-wrap items-center justify-center gap-3 mt-4 print:hidden">
      <button
        onClick={downloadAsWord}
        className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-white px-4 py-2 font-headline text-[12px] font-bold text-emerald-700 shadow-sm transition-all hover:bg-emerald-50 active:scale-95"
      >
        <FileText size={16} />
        Download Word (.doc)
      </button>
    </div>
  );
}
